//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBot.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADSList
    {
        public int ID { get; set; }
        public string uID { get; set; }
        public string link { get; set; }
        public string discription { get; set; }
        public string pic { get; set; }
        public string GUID { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> OneLiner { get; set; }
    }
}
