//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBot.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class agent
    {
        public int id { get; set; }
        public string agentuid { get; set; }
        public string agentname { get; set; }
        public string agentnumber { get; set; }
        public Nullable<int> sellcount { get; set; }
        public Nullable<int> FreeBalance { get; set; }
        public Nullable<int> UsedBalance { get; set; }
    }
}
