//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBot.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallBack
    {
        public int ID { get; set; }
        public string Identifier { get; set; }
        public string CallBack1 { get; set; }
    }
}
