//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBot.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HireList
    {
        public int ID { get; set; }
        public string ProjectID { get; set; }
        public string employeeID { get; set; }
        public string FreeLancerID { get; set; }
        public string discription { get; set; }
        public Nullable<bool> @checked { get; set; }
        public Nullable<bool> hirefinished { get; set; }
        public Nullable<bool> Disable { get; set; }
        public string ChnnlMssgID { get; set; }
    }
}
