//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBot.Models.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class telbotZB_dbEntities : DbContext
    {
        public telbotZB_dbEntities()
            : base("name=telbotZB_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<agent> agents { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<HireList> HireLists { get; set; }
        public virtual DbSet<ADSList> ADSLists { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<AdsChannel> AdsChannels { get; set; }
        public virtual DbSet<AdsGroup> AdsGroups { get; set; }
        public virtual DbSet<AdsBusiness> AdsBusinesses { get; set; }
    }
}
