//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBot.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int ID { get; set; }
        public string ProjectId { get; set; }
        public string uid { get; set; }
        public string category { get; set; }
        public string dicription { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<bool> ProjectFinished { get; set; }
        public Nullable<bool> disable { get; set; }
        public string ChnnlMssgID { get; set; }
    }
}
