//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBot.Models.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int PK { get; set; }
        public string uID { get; set; }
        public string fullname { get; set; }
        public string number { get; set; }
        public Nullable<bool> finishedregister { get; set; }
        public string registermode { get; set; }
        public Nullable<byte> registerstep { get; set; }
        public string invcode { get; set; }
        public Nullable<int> agent { get; set; }
        public Nullable<byte> projectstep { get; set; }
        public Nullable<bool> ishireing { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<byte> adsStep { get; set; }
        public Nullable<bool> IsBanned { get; set; }
        public string sendtoEMPmessageID { get; set; }
        public Nullable<byte> DisableStep { get; set; }
        public Nullable<int> AdsChance { get; set; }
        public Nullable<int> HireChance { get; set; }
        public Nullable<int> ProjectChance { get; set; }
    }
}
